* Personal Emacs Configuration 🏡
This repository contains the setup for my Emacs configuration. It's useful for a wide variety of things, but of course you should fork this and edit it for your own purposes.

It works best on macOS and in a graphical frame. For the best experience, use [[https://github.com/railwaycat/homebrew-emacsmacport][Yamamoto Mitsuharu's Emacs macOS port]] or [[https://github.com/jimeh/emacs-builds][Emacs Builds for macOS]]. It /might/ work on Linux or WSL, and almost certainly won't work under Windows without substantial changes. 

This file is split up by packages, grouped in a way that I think is logical. At run-time, ~early-init.el~ splits this file into many smaller elisp files that are then read by Emacs as one combined ~README.el~. This happens at every startup and is a bit slow, so I recommend only restarting Emacs when absolutely needed, since almost all Emacs operations can be done without needing to restart Emacs, including updating and installing new packages.

** How to Install 💻
Firstly, make sure the following programs are installed:
- ~git~ (used by ~elpaca~)
- ~gcc~ and ~cmake~, used for ~vterm~ (optional, if not just say ~n~ when asked on install and add ~:disable t~ to ~vterm~)

Ideally in a future version of this configuration, it would prompt you to install these, but that's currently not the case. I'll fix that eventually.

~git clone~ this into ~/.emacs.d~, then start Emacs. On the first boot, this is very slow. It gets much better after the first run completes. On my machine, it takes about 6 seconds for Emacs to start. If this is substantially slower on your machine, make sure you're using Emacs 30 or newer, as the GCC JIT was not enabled before then & this config may cause extreme slowdowns in some cases without it.

** Things To Improve 🤔
- Make sure that Emacs makes sure you have all the packages you need, and gracefully degrades on failure
- Add ~puni~ rather than ~paredit~
- Add ~consult-gh~ support
** The Actual Configuration 📖
*** Package Manager & Key Tools
The default ~package.el~ is disabled by ~early-init.el~. Let's use ~Elpaca~ to manage packages, since we defined it in ~init.el~:
#+begin_src emacs-lisp
  (elpaca elpaca-use-package
  	(elpaca-use-package-mode))

  (elpaca-wait)
#+end_src
And then install ~diminish~ and ~transient~ since we'll call them a lot later:
#+begin_src emacs-lisp
  (use-package diminish
    :ensure (:wait t)
    :demand t)

  (use-package transient
    :ensure (:wait t)
    :demand t)

  (elpaca-wait)
#+end_src
We need to now ~exec-path-from-shell~ first, before anything else:
#+begin_src emacs-lisp
  (use-package exec-path-from-shell
    :ensure (:wait t)
    :demand t
    :init
    (when (memq window-system '(mac ns x))
      (exec-path-from-shell-initialize)))
#+end_src
Now sync everything, one more time.
#+begin_src emacs-lisp
  (elpaca-wait)
#+end_src
*** Graphics Fixes
We didn't have the frame loaded and rendered in until this point, so we couldn't fix stuff that was really visually annoying. Now, we can.
#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (pixel-scroll-mode)
  (pixel-scroll-precision-mode)
  (global-prettify-symbols-mode 1)
  (setq window-sides-vertical t)

  (setq use-file-dialog nil
    	   use-dialog-box nil
    	   inhibit-startup-screen t)

  (setq mac-command-modifier 'meta)

  (setq use-package-compute-statistics t)

  (setopt line-number-mode t
    		column-number-mode t
    		x-underline-at-descent-line nil
    		switch-to-buffer-obey-display-actions t
    		show-trailing-whitespace nil
    		indicate-buffer-boundaries 'left)

  ;; horizontal mouse scrolling
  (setopt mouse-wheel-tilt-scroll t
    		mouse-wheel-flip-direction t)

  ;; line numbers in programming modes
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (setopt display-line-numbers-width 3)

  ;; wrap text in visual modes
  (add-hook 'text-mode-hook 'visual-line-mode)
  ;; hack to hide visual line mode
  ;; we don't need to see it. we'll *know*.
  (use-package emacs
    :diminish visual-line-mode)

  ;; modes where hl-line is enabled
  (let ((hl-line-hooks '(text-mode-hook prog-mode-hook)))
    (mapc (lambda (hook) (add-hook hook 'hl-line-mode)) hl-line-hooks))
#+end_src
*** Behavior Fixes
These go first, so that even if loading the rest of this file fails, there's at least some fixes to the parts of Emacs which can largely be considered to be "bad defaults". 
#+begin_src emacs-lisp
  ;; genuinely baffling how this isn't the default
  (global-set-key (kbd "C-x C-b") 'ibuffer)

  (require 'ibuffer)

  ;; hate to use a package here, but this should always work
  (use-package ibuffer-vc
    :ensure t
    :config
    (require 'ibuffer-vc)
    (add-hook 'ibuffer-hook
  	    (lambda ()
  	      (ibuffer-vc-set-filter-groups-by-vc-root)
  	      (unless (eq ibuffer-sorting-mode 'alphabetic)
  		(ibuffer-do-sort-by-alphabetic)))))

  ;; disable bidirectional text almost always
  (setq-default bidi-display-reordering 'left-to-right
                bidi-paragraph-direction 'left-to-right)
  (setq bidi-inhibit-bpa t)

  ;; don't fontify until we're done typing for speed
  (setq redisplay-skip-fontification-on-input t)

  ;; make lsp mode faster
  (setq read-process-output-max (* 16 1024 1024)) ;; 16MB

  ;; don't render the cursor in non-focused windows
  (setq-default cursor-in-non-selected-windows nil)
  (setq highlight-nonselected-windows nil)

  ;; always save our clipboard before adding new items to the kill ring
  ;; this is so annoying I'm confused it's not default
  (setq save-interprogram-paste-before-kill t)

  ;; no kill ring dupes
  (setq kill-do-not-save-duplicates t)

  ;; if we save a file that should be executable, chmod it for us
  (add-hook 'after-save-hook
            #'executable-make-buffer-file-executable-if-script-p)

  ;; don't check to see if a file is remote on find-file-at-point
  (setq ffap-machine-p-known 'reject)

  ;; resize windows proportionally
  (setq window-combination-resize t)

  ;; the below makes C-x 1 just focus on a single window, and easily restores them
  (winner-mode +1)

  ;; fix file sizes
  (define-ibuffer-column size-h
    (:name "Size"
  	 :inline t)
    (file-size-human-readable (buffer-size)))

  (setq ibuffer-formats
        '((mark modified read-only locked " "
  	      (name 18 18 :left :elide)
  	      " "
  	      (size-h 9 -1 :right)
  	      " "
  	      (mode 16 16 :left :elide)
  	      " "
  	      filename-and-process)))

  ;; need for code snippets
  (require 'org-tempo)

  ;; reread files from disk
  (setopt auto-revert-avoid-polling t)
  (setopt auto-revert-interval 5)
  (setopt auto-revert-check-vc-info t)
  (global-auto-revert-mode)

  ;; move through windows with Ctrl-<arrow keys>
  (windmove-default-keybindings 'control)

  ;; fix archaic defaults
  (setopt sentence-end-double-space nil)

  ;; make right-click do something sensible
  (when (display-graphic-p)
    (context-menu-mode))

  ;; don't litter file system with *~ backup files; put them all inside
  ;; ~/.emacs.d/backup or wherever
  (let ((auto-dir (expand-file-name "autosaves/" user-emacs-directory))
        (backup-dir (expand-file-name "backups/" user-emacs-directory)))
    (dolist (dir (list auto-dir backup-dir))
      (unless (file-exists-p dir) (make-directory dir t)))
    (setq backup-directory-alist `(("." . ,backup-dir))
  	auto-save-file-name-transforms `((".*" ,auto-dir t))
  	auto-save-list-file-prefix (concat auto-dir ".saves-")))

  ;; highlight urls
  ;; if we don't set it this way, xwidget breaks
  (goto-address-prog-mode)

  ;; show the fill column
  (setq-default display-fill-column-indicator-column 80)
  (add-hook 'prog-mode-hook #'display-fill-column-indicator-mode)

  ;; force compliation to look nicer
  (add-hook 'complilation-mode-hook 'visual-line-mode)

  ;; nicer prompts
  (fset 'yes-or-no-p 'y-or-n-p)
  ;; doesn't work in older emacs
  (when (version< emacs-version "29")
    (when (boundp 'use-short-answers)
      (setopt use-short-answers t)))

  ;; remember where we are and what we're doing
  (save-place-mode 1)
  (setq history-length 1000
        recentf-max-saved-items 1000)
  (recentf-mode 1)
  (savehist-mode 1)

  ;; recenter the view when we return to a known file
  (advice-add 'save-place-find-file-hook :after
              (lambda (&rest _)
                (when buffer-file-name (ignore-errors (recenter)))))

  ;; save the kill ring to the hist function
  (setq savehist-additional-variables
        '(search-ring regexp-search-ring kill-ring))

  ;; but text properties can get large, so strip them
  ;; thanks, Doom Emacs!
  (add-hook 'savehist-save-hook
            (lambda ()
              (setq kill-ring
                    (mapcar #'substring-no-properties
                            (cl-remove-if-not #'stringp kill-ring)))))

  ;; always use UTF-8
  (prefer-coding-system 'utf-8)
  (setq locale-coding-system 'utf-8)
  (unless *is-a-windows*
    (set-selection-coding-system 'utf-8))

  ;; when we have two unique buffers, act like it
  (require 'uniquify)
  (setq uniquify-separator " • "
        uniquify-after-kill-buffer-p t
        uniquify-ignore-buffers-re "^\\*"
        uniquify-buffer-name-style 'reverse)

  ;; handle long files
  (when (fboundp 'so-long-enable)
    (add-hook 'after-init-hook 'so-long-enable))

  ;; when we're a mac, use mdfind not find
  (when *is-a-mac*
    (setq-default locate-command "mdfind"))

  ;; make TRAMP faster
  (use-package tramp
    :config
    (connection-local-set-profile-variables
     'remote-direct-async-process
     '((tramp-direct-async-process . t)))
    (connection-local-set-profiles
     '(:application tramp :protocol "ssh")
     'remote-direct-async-process)
    ;; Tips to speed up connections
    ;; change tramp-verbose if you're having issues
    (setq tramp-verbose 3)
    (setq tramp-chunksize 2000)
    (setq tramp-ssh-controlmaster-options nil))

  ;; make dired less awful to look at
  (setq dired-listing-switches "-alh")

  ;; fix the ls related issues on macOS & Unix
  (if (or *is-a-mac* *is-a-haiku* *is-a-unix*)
      (progn
        (setq ls-lisp-use-insert-directory-program nil
  	    dired-use-ls-dired nil)
        (require 'ls-lisp)))
#+end_src
*** Utility Functions
These are things that I use that are nice to have but aren't part of GNU Emacs. Although many of them are basically replaced by ~crux~ at this point, it's nice to keep around a vanilla implementation in case packages can't be installed.
#+begin_src emacs-lisp
  ;; redefine the annoying GNU advertisement
  (defun display-startup-echo-area-message ()
    "Gets rid of that annoying GNU advertisement."
    (message "[init.el] Init complete. Get out there!"))

  ;; kill the buffer and file
  (defun personal/delete-this-file-and-buffer ()
    "Delete the current file and kill its buffer."
    (interactive)
    (unless (buffer-file-name)
      (error "Nothing is being edited right now!"))
    (when (y-or-n-p (format "Really delete '%s'? "
  			  (file-name-nondirectory buffer-file-name)))
      (delete-file (buffer-file-name))
      (kill-this-buffer)
      (message "Buffer killed.")))

  ;; Rename the buffer and file
  (defun personal/rename-this-file-and-buffer (new-name)
    "Renames both current buffer and file it's visiting to NEW-NAME."
    (interactive "sNew name: ")
    (let ((name (buffer-name))
  	(filename (buffer-file-name)))
      (unless filename
        (error "Buffer '%s' is not visiting a file!" name))
      (progn
        (when (file-exists-p filename)
  	(rename-file filename new-name 1))
        (set-visited-file-name new-name)
        (rename-buffer new-name)
        (message "Buffer renamed."))))

  (defun personal/toggle-delete-other-windows ()
    "Delete other windows in frame if any, or restore previous window config."
    (interactive)
    (if (and winner-mode
             (equal (selected-window) (next-window)))
        (winner-undo)
      (delete-other-windows)))

  (global-set-key (kbd "C-x 1")
                  #'personal/toggle-delete-other-windows)

  ;; Simpify our life.
  (defun personal/revert-to-two-windows ()
    "Delete all other windows and split it into two."
    (interactive)
    (delete-other-windows)
    (split-window-right))

  ;; deal with adding extensions for a mode.
  (defun add-auto-mode (mode &rest patterns)
    "Add entries to `auto-mode-alist' to use `MODE' for all given file `PATTERNS'."
    (dolist (pattern patterns)
      (add-to-list 'auto-mode-alist (cons pattern mode))))

  ;; stops flycheck from yelling at you
  (defun personal/headerise-elisp ()
    "Add minimal header and footer to an elisp buffer in order to placate flycheck."
    (interactive)
    (let ((fname (if (buffer-file-name)
  		   (file-name-nondirectory (buffer-file-name))
  		 (error "This buffer is not visiting a file"))))
      (save-excursion
        (goto-char (point-min))
        (insert ";;; " fname " --- Insert description here -*- lexical-binding: t -*-\n"
  	      ";;; Commentary:\n"
  	      ";;; Code:\n\n")
        (goto-char (point-max))
        (insert ";;; " fname " ends here\n"))))

  ;; kill all buffers instantly
  ;; genuinely WHY is this not already built-in
  (defun personal/close-all-buffers ()
    "Kill all buffers without regard for their origin."
    (interactive)
    (mapc 'kill-buffer (buffer-list)))
  (global-set-key (kbd "C-M-s-k") 'close-all-buffers)

  ;; indent the whole buffer automatically
  (defun personal/indent-buffer ()
    (interactive)
    (indent-region (point-min) (point-max)))

  ;; quickly visit our configuration
  (defun personal/config-visit ()
    (interactive)
    (find-file "~/.emacs.d/config.org"))
#+end_src
*** Packages: Utility
This category is for packages which extend Emacs without adding brand new features. Basically just tweaks or minor extensions of existing features.
**** ~osx-trash~
Really nice fix for the fact that stock Emacs can't do this.
#+begin_src emacs-lisp
  (use-package osx-trash
    :ensure t
    :if *is-a-mac*
    :init
    (if (executable-find "trash")
      (setq osx-trash-command "trash"))
    (osx-trash-setup))
  (setopt delete-by-moving-to-trash t)
#+end_src
**** ~which-key~
This is in stock as of Emacs 30, so this just enables it with diminish, and doesn't download anything.
#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :diminish
    :config
    (which-key-mode))
#+end_src
**** ~sudo-edit~ & ~auto-sudoedit~
We want to be able to edit as root, but only on Unix and Linux.
#+begin_src emacs-lisp
  (use-package sudo-edit
    :if (or *is-a-linux* *is-a-unix*)
    :ensure t)
#+end_src
Also, automatically retry if we can't do it for whatever reason.
#+begin_src emacs-lisp
  (use-package auto-sudoedit
    :ensure t
    :diminish
    :init
    (require 'auto-sudoedit)
    (auto-sudoedit-mode 1))
#+end_src
**** ~async~
#+begin_src emacs-lisp
  (use-package async
    :ensure t
    :config
    (async-bytecomp-package-mode 1)
    (dired-async-mode 1))
#+end_src
**** ~editorconfig~
#+begin_src emacs-lisp
  (use-package editorconfig
    :ensure t
    :diminish
    :config
    (editorconfig-mode 1))
#+end_src
**** ~whole-line-or-region~
This is extremely useful since we often want to run a command on the line, but don't want to bother with painstakingly selecting the right region
#+begin_src emacs-lisp
  (use-package whole-line-or-region
    :ensure t
    :diminish whole-line-or-region-local-mode
    :hook (after-init . whole-line-or-region-global-mode))
#+end_src
**** ~wgrep~
This package lets us mass edit search results, which is amazing!
#+begin_src emacs-lisp
  (use-package wgrep
    :ensure t
    :config
    (setq wgrep-auto-save-buffer t))
#+end_src
**** ~anzu~
Displays the amount of matches for any given search, which is quite useful.
#+begin_src emacs-lisp
  (use-package anzu
    :ensure t
    :diminish 
    :init
    (global-anzu-mode +1))
#+end_src
**** ~scratch~
It's often useful to pop open a scratch buffer for a given mode without making a file. So useful that we need a hotkey for it.
#+begin_src emacs-lisp
  (use-package scratch
    :ensure t
    :bind ("C-c s" . scratch))
#+end_src
**** ~switch-window~
Extremely useful when you've got a lot of these on the screen.
#+begin_src emacs-lisp
  (use-package switch-window
    :ensure t
    :config
    (setq switch-window-shortcut-style 'qwerty)
    (setq switch-window-timeout nil)
    :bind
    ("C-x o". switch-window))
#+end_src
**** ~other-frame-window~
Emacs has an /okay/ window manager, but it's preferable to use the real OS one. So to fix this, we can use this package, so that we can spawn buffers in other windows. The one caveat is that if you make too many windows, it can become dangerous, as you could accidentally delete your primary Emacs window. Use with care.
#+begin_src emacs-lisp
  (use-package other-frame-window
    :ensure t
    :diminish
    :init
    (other-frame-window-mode))
#+end_src
**** ~osx-clipboard-mode~
Allows the use of the macOS clipboard, even if we're not on the terminal
#+begin_src emacs-lisp
  (use-package osx-clipboard
    :if (and (not (window-system)) *is-a-mac*)
    :ensure t
    :diminish
    :init
    (osx-clipboard-mode +1))
#+end_src
**** ~restart-emacs~
Restart Emacs from within Emacs! Useful for config updates.
#+begin_src emacs-lisp
  (use-package restart-emacs
    :ensure t)
#+end_src
**** ~edit-indirect~
Allows for editing a part of a buffer in another buffer.
#+begin_src emacs-lisp
  (use-package edit-indirect
    :ensure t)
#+end_src
**** ~quickrun~
The equivalent of clicking the big "Run" button in an IDE. Basically compiles and executes the buffer.
#+begin_src emacs-lisp
  (use-package quickrun
    :ensure t)
#+end_src
**** ~makefile-executor~
Allows us to execute certain targets at any buffer in a project.
#+begin_src emacs-lisp
  (use-package makefile-executor
    :ensure t
    :config
    (add-hook 'makefile-mode-hook 'makefile-executor-mode))
#+end_src
**** ~lorem-ipsum~
Quick filler text, if needed.
#+begin_src emacs-lisp
  (use-package lorem-ipsum
    :ensure t)
#+end_src
**** ~crux~
A bunch of extremely useful functions indeed! It adds all the things that the Emacs devs seemingly forgot to put into the final version.
#+begin_src emacs-lisp
  (use-package crux
    :ensure t)
#+end_src
**** ~insert-kaomoji~
Incredibly useful package.
#+begin_src emacs-lisp
  (use-package insert-kaomoji
    :ensure t)
#+end_src
**** ~insert-random~
Maybe useful under a particularly strange set of circumstances?
#+begin_src emacs-lisp
  (use-package insert-random
    :ensure t)
#+end_src
**** ~evil-nerd-commenter~
Despite the name, it's not really required to use ~evil~ for it. What it actually does is quickly uncomments or comments out a line. It's a bit smarter than the default one because it works on multiple lines if you combine it with ~C-u~.
#+begin_src emacs-lisp
  (use-package evil-nerd-commenter
    :ensure t
    :bind ("M-;" . evilnc-comment-or-uncomment-lines))
#+end_src
**** ~visual-replace~
Shows the replacements that we're going to do. It shows what the buffer will look like after the replacement.
#+begin_src emacs-lisp
  (use-package visual-replace
    :ensure t
    :diminish
    :init
    (visual-replace-global-mode 1))
#+end_src
**** ~vlf~
Sometimes, files are so big that Emacs simply cannot handle them. This solves that problem by making the performance better. I recommend using this on text files over 100MB, rather than ~so-long-mode~ which only really works well on smaller buffers.
#+begin_src emacs-lisp
  (use-package vlf
    :ensure t)
#+end_src
*** Packages: Appearance
This category is for packages which make Emacs' interface look nicer.
**** Themes: ~gruvbox~, ~solarized~, ~vscode-dark-plus~, ~waher~, ~modus~
Gruvbox is simply the best theme ever invented, but sometimes I like to have some others. All are installed, so it's easy to change them. At present, the theme system also can intelligent switch between night and day mode. Nice!
#+begin_src emacs-lisp
  ; ignore asking if custom themes are safe
  (setq custom-safe-themes t)

  (use-package solarized-theme
    :ensure t
    :config
    (setq solarized-high-contrast-mode-line nil
  	  solarized-distinct-doc-face t
  	  solarized-distinct-fringe-background t
  	  solarized-emphasize-indicators t
  	  x-underline-at-descent-line t)
    :init
    (load-theme 'solarized-selenized-black t))

#+end_src
And then, of course, ~auto-dark-mode~:
#+begin_src emacs-lisp
  ;; this actually does nothing at the moment but it's nice to have
  (use-package auto-dark
    :ensure t
    :custom
    (auto-dark-themes '((solarized-selenized-black) (solarized-selenized-white)))
    (auto-dark-polling-interval-seconds 5)
    (auto-dark-allow-osascript t)
    :hook
    (auto-dark-dark-mode
     . (lambda ()
  	 (set-face-background 'why-this-annotate-heat-map-cold "#203448")
  	 (set-face-background 'why-this-annotate-heat-map-warm "#382f27")
  	 (message "[auto-dark] Dark mode theme automatically applied")))
    (auto-dark-light-mode
     . (lambda ()
  	 (set-face-background 'why-this-annotate-heat-map-cold "#dde3f4")
  	 (set-face-background 'why-this-annotate-heat-map-warm "#f0e0d4")
  	 (message "[auto-dark] Light mode theme automatically applied")))
    :init (auto-dark-mode))
#+end_src
**** Modeline: ~telephone-line~
It's a bit nicer looking than the powerbars, which are too flashy for me.
#+begin_src emacs-lisp
  (use-package telephone-line
    :ensure t
    :if window-system
    :diminish telephone-line-mode
    :config
    (setq telephone-line-lhs
  	  '((evil   . (telephone-line-flycheck-segment))
  	    (accent . (telephone-line-vc-segment
  		       telephone-line-process-segment))
  	    (nil    . (telephone-line-projectile-segment
  		       telephone-line-buffer-segment)))
  	  telephone-line-rhs
  	  '((nil    . (telephone-line-position-segment))
  	    (accent . (telephone-line-major-mode-segment))
  	    ;; I used to put minor mode here but it's way too annoying in practice.
  	    ;; This is where our LSP info will live
  	    (evil   . (telephone-line-misc-info-segment)))
  	  telephone-line-height 24
  	  ;; different layouts don't render well on macOS.
  	  telephone-line-primary-left-separator 'telephone-line-nil
  	  telephone-line-secondary-left-separator 'telephone-line-nil
  	  telephone-line-primary-right-separator 'telephone-line-nil
  	  telephone-line-secondary-right-separator 'telephone-line-nil)
    (telephone-line-mode 1))
#+end_src
**** ~solaire~
Makes the buffers that aren't part of real files a different color than those that are.
#+begin_src emacs-lisp
  (use-package solaire-mode
    :ensure t
    :diminish
    :config
    (solaire-global-mode +1))
#+end_src
**** ~persist-text-scale~
Persist the scale of the text between reloads!
#+begin_src emacs-lisp
  (use-package persist-text-scale
    :ensure t
    :custom
    ;; once every seven minutes
    (persist-text-scale-autosave-interval (* 7 60))
    :init
    (persist-text-scale-mode 1))
#+end_src
**** ~modern-fringes~
This replaces the default bitmaps with some more readable ones.
#+begin_src emacs-lisp
  (use-package modern-fringes
    :ensure t
    :diminish
    :init
    (modern-fringes-mode))
#+end_src
**** ~ligatures~ and ~fontaine~
They look /so good/ with the right font. This config assumes you use JetBrains Mono, as this section won't work with any other font.
#+begin_src emacs-lisp
  ;; obviously, this must be set first
  (set-frame-font "JetBrains Mono 12" nil t)

  (setq fontaine-latest-state-file
	(locate-user-emacs-file "fontaine-latest-state.eld"))
#+end_src
And now for the ligatures:
#+begin_src emacs-lisp
  (use-package ligature
    :ensure t
    :diminish
    :config
    ;; the JetBrains specific part
    (ligature-set-ligatures 'prog-mode '("--" "---" "==" "===" "!=" "!==" "=!="
				"=:=" "=/=" "<=" ">=" "&&" "&&&" "&=" "++" "+++" "***" ";;" "!!"
				"??" "???" "?:" "?." "?=" "<:" ":<" ":>" ">:" "<:<" "<>" "<<<" ">>>"
				"<<" ">>" "||" "-|" "_|_" "|-" "||-" "|=" "||=" "##" "###" "####"
				"#{" "#[" "]#" "#(" "#?" "#_" "#_(" "#:" "#!" "#=" "^=" "<$>" "<$"
				"$>" "<+>" "<+" "+>" "<*>" "<*" "*>" "</" "</>" "/>" "<!--" "<#--"
				"-->" "->" "->>" "<<-" "<-" "<=<" "=<<" "<<=" "<==" "<=>" "<==>"
				"==>" "=>" "=>>" ">=>" ">>=" ">>-" ">-" "-<" "-<<" ">->" "<-<" "<-|"
				"<=|" "|=>" "|->" "<->" "<~~" "<~" "<~>" "~~" "~~>" "~>" "~-" "-~"
				"~@" "[||]" "|]" "[|" "|}" "{|" "[<" ">]" "|>" "<|" "||>" "<||"
				"|||>" "<|||" "<|>" "..." ".." ".=" "..<" ".?" "::" ":::" ":=" "::="
				":?" ":?>" "//" "///" "/*" "*/" "/=" "//=" "/==" "@_" "__" "???"
				"<:<" ";;;"))
    (global-ligature-mode t))
#+end_src
**** ~ultra-scroll~
This is the best package at least on macOS, and probably the best on Linux too.
#+begin_src emacs-lisp
  (use-package ultra-scroll
    :ensure t
    :if window-system
    :diminish
    :config
    (ultra-scroll-mode 1))
#+end_src
**** ~dimmer~
This package is finally fixed! Nice, smooth dimming of inactive buffers, that now works relatively well regardless of themes. Nice!
#+begin_src emacs-lisp
  (use-package dimmer
    :ensure t
    :disabled t ;; nope broken again
    :if window-system
    :diminish
    :config
    (setq dimmer-adjustment-mode :foreground
	  dimmer-fraction 0.3)
    (require 'dimmer)
    (dimmer-configure-which-key)
    (dimmer-configure-helm)
    (dimmer-mode t))
#+end_src
**** ~beacon~
#+begin_src emacs-lisp
  (use-package beacon
    :ensure t
    :diminish
    :config
    (beacon-mode 1))
#+end_src
**** ~huecycle~
Makes certain parts of the screen change color when idle. A nicer alternative to ~zone~. May want to disable; raises CPU while idle. This simplifies life a lot.
#+begin_src emacs-lisp
  ;; TODO: doesn't actually work, package is bugged
  (use-package huecycle
    :disabled t
    :init
    (huecycle-set-faces
     ((background . hl-line)
      :random-color-hue-range (0.0 1.0)
      :random-color-saturation-range (0.4 0.6)
      :random-color-luminance-range (0.2 0.3))
      :speed 3.0)
    (huecycle-when-idle 10))
#+end_src
**** ~pulsing-cursor~
Blink and fade the cursor for a RGB-lighting like effect.
#+begin_src emacs-lisp
  (use-package pulsing-cursor
    :elpaca (pulsing-cursor :host github :repo "jasonjckn/pulsing-cursor")
    :demand t
    :diminish
    :config
    (pulsing-cursor-mode +1))
#+end_src
**** ~goggles~
#+begin_src emacs-lisp
  ;; flash the text that we're looking at when editing
  (use-package goggles
    :ensure t
    :diminish
    :hook ((prog-mode text-mode) . goggles-mode)
    :config
    (setq-default goggles-pulse t))
#+end_src
**** ~indent-bars~
Highlight the code level we're at.
#+begin_src emacs-lisp
  (use-package indent-bars
    :ensure t
    :diminish
    :hook (prog-mode . indent-bars-mode)
    :config
    ;; come back to this in Emacs 31
    (setq indent-bars-prefer-character t))
#+end_src
**** ~highlight-escape-sequences~
#+begin_src emacs-lisp
  (use-package highlight-escape-sequences
    :ensure t
    :diminish hes-mode
    :hook (after-init . hes-mode))
#+end_src
**** ~highlight-numbers~
This package highlights numerical literals, not just any random number
#+begin_src emacs-lisp
  (use-package highlight-numbers
    :ensure t
    :diminish
    :hook (prog-mode . highlight-numbers-mode))
#+end_src
**** ~page-break-lines~
Shows us when the page break character is there in our text.
#+begin_src emacs-lisp
  (use-package page-break-lines
    :ensure t
    :diminish
    :hook (after-init . global-page-break-lines-mode))
#+end_src
**** ~rainbow-delimiters~
This only applies to parenthesis, but it makes Lisp a lot easier to read!
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :diminish rainbow-delimiters-mode
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src
**** ~rainbow-mode~
Make hex color codes match their values.
#+begin_src emacs-lisp
  (use-package rainbow-mode
    :ensure t
    :diminish
    :hook ((emacs-lisp-mode . rainbow-mode)
	   (help-mode . rainbow-mode)
	   ((css-mode html-mode sass-mode) . rainbow-mode)))
#+end_src
**** ~comet-trail~
Make the cursor have a nice effect, like ~beacon~ but for within-buffer moves. This thing is so slow because it seemingly recalculates on *every move*...
#+begin_src emacs-lisp
  (use-package comet-trail
    :disabled t
    :hook ((prog-mode . comet-trail-mode)
	   (text-mode . comet-trail-mode)
	   (fundamental-mode . comet-trail-mode))
    :config
    (setq comet-trail-minimum-distance 50
	  comet-trail-speed 0.25))
#+end_src
**** ~symon~
An extremely small system monitor in the idle modeline. Very good for full-screen Emacs, or when using X over SSH.
#+begin_src emacs-lisp
  (use-package symon
    :ensure t
    :diminish
    :config
    (symon-mode))
#+end_src
**** ~cowsay~
Add a little fortune to our scratch buffers.
#+begin_src emacs-lisp
  ;; make the image
  (use-package cowsay
    :ensure (:wait t)
    :init
    (cowsay-load-cow-file (expand-file-name "tux.cow" user-emacs-directory)))


  ;; wrap the cow in comments
  (defun personal/prefix-comment (arg)
    "Comment ARG with semicolons."
    (interactive)
    (mapconcat
     (lambda (x) (concat ";; " x))
     (split-string arg "\n" t) "\n"))

  ;; now actually set our scratch buffer
  (setq inhibit-startup-message t
        initial-scratch-message (concat (personal/prefix-comment  (cowsay-string "Emacs has finished starting." "tux")) "\n\n"))


#+end_src
**** ~org-superstar-mode~
Makes ~org-mode~ have some prettier-looking bullet points!
#+begin_src emacs-lisp
  (use-package org-superstar
    :ensure t
    :diminish
    :hook (org-mode . org-superstar-mode))
#+end_src
**** ~dired-fl~
This adds some special fonts to the ~dired~ mode to make it nicer.
#+begin_src emacs-lisp
  (use-package diredfl
    :ensure t
    :diminish
    :init
    (diredfl-global-mode))
#+end_src
**** ~pangu-spacing~
Improves aesthetics of having Japanese characters and English ones side by side. 美しい日本語入力!
#+begin_src emacs-lisp
  (use-package pangu-spacing
    :ensure t
    :diminish
    :init
    (global-pangu-spacing-mode 1))
#+end_src
**** ~kind-icon~
Despite the name we never actually use any icons, at least not on the terminal. This just adds a little symbol to ~corfu~ that shows you what exactly you're completing.
#+begin_src emacs-lisp
  (use-package kind-icon
    :ensure t
    :after corfu
    :custom
    (kind-icon-use-icons nil)
    ; (kind-icon-default-face 'corfu-default) ; only needed with blend-background
    :config
    (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))
#+end_src
**** ~fancy-compile~
Running the ~compile~ command now does more useful things with better syntax highlighting.
#+begin_src emacs-lisp
  (use-package fancy-compilation
    :ensure t
    :diminish
    :init
    (fancy-compilation-mode))
#+end_src
**** ~olivetti~
This package allows you to turn on edges to your buffer, kind of like in Microsoft Word with its page limit. This way, no matter how big your frame is, your buffer still kinda looks nice. Which is a cool feature to have for editing text documents, so that text isn't strewn across the whole page.
#+begin_src emacs-lisp
  (use-package olivetti
    :ensure t)
#+end_src
**** ~pretty-sha-path~
Tidy up GUIX/Nix directories when you see them in Emacs.
#+begin_src emacs-lisp
  (use-package pretty-sha-path
    :ensure t
    :diminish
    :init
    (global-pretty-sha-path-mode))
#+end_src
**** ~ns-auto-titlebar~
Set a transparent titlebar on Emacs macOS builds.
#+begin_src emacs-lisp
  (use-package ns-auto-titlebar
    :ensure t
    :diminish
    :if *is-a-mac*
    :config
    (ns-auto-titlebar-mode))
#+end_src
*** Packages: Overhauls
Some parts of Emacs are fundamentally broken. These packages replace those features outright with new things. I note what's being replaced.
**** ~eat~: Replacement of ~ansi-term~
Fine on every OS but is a bit slower than ~vterm~.
#+begin_src emacs-lisp
  (use-package eat
    :ensure t
    :custom
    (eat-term-name "xterm")
    :init
    (add-hook 'eshell-load-hook #'eat-eshell-mode)
    (add-hook 'eshell-load-hook #'eat-eshell-visual-command-mode))
#+end_src
**** ~vterm~: Another Replacement of ~ansi-term~
Faster but requires the compiled module so this can fail quite dramatically. It doesn't match theme colors, because the colors you want for editing code vs running commands should be different.
#+begin_src emacs-lisp
  (use-package vterm
    :ensure t
    :if (not *is-a-windows*)
    :init
    ;; use classic terminal colors
    ;; also, this gives us a dark mode terminal all the time
    (setq vterm-color-black   "#000000"
  	vterm-color-white   "#ffffff"
  	vterm-color-red     "#ff5c57"
  	vterm-color-green   "#5af78e"
  	vterm-color-yellow  "#f3f99d"
  	vterm-color-blue    "#57c7ff"
  	vterm-color-magenta "#ff6ac1"
  	vterm-color-cyan    "#9aedfe"))
#+end_src
**** ~detached~: Async Command Spawner
TODO: seems useful, but need to read up more on it.
#+begin_src emacs-lisp
  (use-package detached
    :ensure t
    :config
    (detached-init)
    :bind (([remap async-shell-command] . detached-shell-command)
           ([remap compile] . detached-compile)
           ([remap recompile] . detached-compile-recompile))
    :custom ((detached-terminal-data-command system-type)
             (detached-terminal-data-command system-type)))
#+end_src
**** ~multi-term~ & ~multi-vterm~: Summon Many Terminals
We often need more than one terminal when we're doing things. Let's add that:
#+begin_src emacs-lisp
  (use-package multi-term
    :ensure t)
#+end_src
Oh, and add that for ~vterm~, too:
#+begin_src emacs-lisp
  ;; (use-package multi-vterm
  ;;   :after vterm
  ;;   :ensure t)
#+end_src
This is such a good feature that stock ~vterm~ should never be used, only ~multi-vterm~.
**** ~jinx~: Replacement of ~flyspell~
Flyspell is the worst. This is a much better alternative with almost no downsides. We'll also fix our dictionary while we're at it.
#+begin_src emacs-lisp
  (use-package jinx
    :ensure t 
    :hook (((text-mode prog-mode) . jinx-mode))
    :bind (("C-;" . jinx-correct))
    :custom
    (jinx-languages "en" "jp")
    (jinx-camel-modes '(prog-mode))
    (jinx-delay 0.01))

  (setopt dictionary-use-single-buffer t
  	    dictionary-server "dict.org")
#+end_src
**** ~dumb-jump~: Replacement of ~xref~
This package lets you put in a symbol in nearly any language and quickly warp to its definition. It's way cooler than it sounds. Note that you use the binding ~M-.~ to activate it, as it's an ~xref~ backend.

Note that this is simply for in-project jumping: if you want to see stuff in libraries external to the project, you need ~lsp~.
#+begin_src emacs-lisp
  (use-package dumb-jump
    :ensure t
    :init
    (add-hook 'xref-backend-functions #'dumb-jump-xref-activate)
    (setq xref-show-definitions-function #'xref-show-definitions-completing-read))
#+end_src
**** ~deadgrep~: Replacement of ~grep~
It's a nicer interface to ~grep~ but faster. It's even better because of the fact that it actually works with ~wgrep~, so you can basically mass edit. No more need for esoteric regexp. Just ~C-c C-p~ in the results buffer, and then ~C-c C-x~ to save the results, mass editing all the things.
#+begin_src emacs-lisp
  (use-package deadgrep
    :ensure t)
#+end_src
**** A Bunch of ~eshell~ Fixes
There's not really one big package that fixes ~eshell~, but a lot of these get really close to a full overhaul.
Here's one that lets us see command feedback, like in ~zsh~:
#+begin_src emacs-lisp
  (use-package eshell-fringe-status
    :ensure t
    :after eshell
    :diminish eshell-fringe-status-mode
    :hook (eshell-mode . eshell-fringe-status-mode))
#+end_src
And we probably want some better suggestion feedback:
#+begin_src emacs-lisp
  (use-package eshell-did-you-mean
    :ensure t
    ; doesn't work on Windows
    :if (or *is-a-linux* *is-a-mac*)
    :after eshell
    :config
    (eshell-did-you-mean-setup))
#+end_src
Lastly, syntax highlighting:
#+begin_src emacs-lisp
  (use-package eshell-syntax-highlighting
    :ensure t
    :diminish eshell-syntax-highlighting-global-mode
    :after eshell
    :config
    (eshell-syntax-highlighting-global-mode +1))
#+end_src
**** ~consult~: Command Enhancements
These commands completely replace their stock components with upgrades. ~M-y~ to open the kill ring is amazing, genuinely. Makes it about 100x more usable.
#+begin_src emacs-lisp
  (use-package consult
    :ensure t
    :bind (
	   ;; Drop-in replacements
	   ("C-x b" . consult-buffer)     ; orig. switch-to-buffer
	   ("M-y"   . consult-yank-from-kill-ring)   ; orig. yank-pop
	   ;; Searching
	   ("M-s r" . consult-ripgrep)
	   ("M-s l" . consult-line)       ; Alternative: rebind C-s to use
	   ("M-s s" . consult-line)       ; consult-line instead of isearch, bind
	   ("M-s L" . consult-line-multi) ; isearch to M-s s
	   ("M-s o" . consult-outline)
	   ;; Isearch integration
	   :map isearch-mode-map
	   ("M-e" . consult-isearch-history)   ; orig. isearch-edit-string
	   ("M-s e" . consult-isearch-history) ; orig. isearch-edit-string
	   ("M-s l" . consult-line)            ; needed by consult-line to detect isearch
	   ("M-s L" . consult-line-multi)      ; needed by consult-line to detect isearch
	   )
    :config
    ;; Narrowing lets you restrict results to certain groups of candidates
    (setq consult-narrow-key "<"))
#+end_src
**** ~vertico~: Better Vertical Completion
Basically exactly what it says. Makes every menu better.
#+begin_src emacs-lisp  
  (use-package vertico
    :ensure t
    :demand t
    :config
    (vertico-mode))

  (use-package vertico-directory
    :ensure nil
    :after vertico
    :bind (:map vertico-map
  		("M-DEL" . vertico-directory-delete-word)))
#+end_src
**** ~marginalia~: Annotations with Completions
Helps you figure out what exactly that option does.
#+begin_src emacs-lisp
  (use-package marginalia
    :ensure t
    :config
    (marginalia-mode))
#+end_src
**** ~orderless~: Global Fuzzy Find
This is a magical package that allows for any matching string to work in a search.
#+begin_src emacs-lisp
  (use-package orderless
    :ensure t
    :config
    (setq completion-styles '(orderless)))
#+end_src
**** ~corfu~: In-Buffer Completion
This is popup completion, which is a feature GNU Emacs has but doesn't use well.
It's a good replacement for ~company~.
#+begin_src emacs-lisp
  (use-package corfu
    :ensure t
    :demand t
    :diminish corfu-mode corfu-popupinfo-mode
    :bind (:map corfu-map
  		("RET" . nil)
  		("M-d" . corfu-popupinfo-toggle))
    ;; if we use eshell, be careful not to autocomplete
    :hook (eshell-mode-hook . (lambda ()
  				(setq-local corfu-auto nil)
  				(corfu-mode)))
    :config
    ;; use corfu in the minibuffer
    (defun corfu-enable-always-in-minibuffer ()
      (unless (or (bound-and-true-p mct--active)
  		    (bound-and-true-p vertico--input))
      (setq-local corfu-auto nil)
      (corfu-mode 1)))
    (add-hook 'minibuffer-setup-hook #'corfu-enable-always-in-minibuffer 1)
    ;; automatic completion!
    (setq corfu-auto t
  	  ;; I don't care what the warnings say, this setting rules
  	  corfu-auto-prefix 2
  	  corfu-quit-no-match 'separator
  	  corfu-echo-documentation nil)
    ;; turn on corfu's plugins
    (corfu-history-mode 1)
    (global-corfu-mode)
    (corfu-popupinfo-mode))
#+end_src
We also want some popups and to have it work in the terminal:
#+begin_src emacs-lisp
  (use-package corfu-terminal
    :if (not (display-graphic-p))
    :ensure t
    :diminish
    :init
    (corfu-terminal-mode))
#+end_src
This is an extremely important package, so we must:
#+begin_src emacs-lisp
  (elpaca-wait)
#+end_src
**** ~cape~: More Completions For ~corfu~
~corfu~ ships with a lot of built in configurations but it's still missing a lot of the functionality that ~company~ ships with. This package adds that back in so that it works properly. I don't want to trigger these manually, so I handle them all through ~corfu~. Also, the dictionary is only turned on selectively for performance reasons. Overall quite useful though. Dict gets better with history and is otherwise quite useless.
#+begin_src emacs-lisp
  (use-package cape
    :ensure t
    :demand t
    :config
    (setq cape-dict-file "/usr/share/dict/words")
    :init
    (add-hook 'completion-at-point-functions #'cape-dabbrev)
    (add-hook 'completion-at-point-functions #'cape-file)
    (add-hook 'completion-at-point-functions #'cape-history))
#+end_src
This is an extremely important package, so we must:
#+begin_src emacs-lisp
  (elpaca-wait)
#+end_src
**** ~helpful~: Help System
#+begin_src emacs-lisp
  (use-package helpful
    :ensure t
    :init
    (global-set-key (kbd "C-h f") #'helpful-callable)
    (global-set-key (kbd "C-h v") #'helpful-variable)
    (global-set-key (kbd "C-h k") #'helpful-key)
    (global-set-key (kbd "C-h x") #'helpful-command)
    ;; this might break some lisp modes
    (global-set-key (kbd "C-c C-d") #'helpful-at-point)
    ;; this overrides GNU Info
    (global-set-key (kbd "C-h F") #'helpful-function))
#+end_src
**** ~ctrlf~: Better ~isearch~
This replaces ~isearch~ but is genuinely an improvement in every way.
#+begin_src emacs-lisp
  (use-package ctrlf
    :ensure t
    :diminish
    :init
    (ctrlf-mode +1))
#+end_src
**** ~mwim~: Better ~C-e~ and ~C-a~
Moves to the next logical line position, not just to the end of the line.
#+begin_src emacs-lisp
  (use-package mwim
    :ensure t
    :diminish
    :init
    (global-set-key (kbd "C-a") 'mwim-beginning)
    (global-set-key (kbd "C-e") 'mwim-end))
#+end_src
**** ~pdf-tools~: Replacement of ~docview~
The existing document viewer is terrible. This is a bit better, but it does require being compiled, so it will almost certainly break on Windows.
#+begin_src emacs-lisp
  (use-package pdf-tools
    :ensure t
    :init
    (pdf-loader-install)
    (add-to-list 'auto-mode-alist '("\\.pdf\\'" . pdf-view-mode)
    (setq-default pdf-view-display-size 'fit-page)))
#+end_src
We should also remember our position within those documents:
#+begin_src emacs-lisp
  (use-package pdf-view-restore
    :ensure t
    :after pdf-tools
    :diminish
    :init
    (setq pdf-view-restore-filename "~/.emacs.d/pdf-view-restore")
    (add-hook 'pdf-view-mode-hook 'pdf-view-restore-mode))
#+end_src
**** ~visual-regexp~: Replacement of ~regexp~
Why use Emacs's ancient regexp format when we can use the much better ones that come with Python? We'll replace only the stuff we're not replacing elsewhere.
#+begin_src emacs-lisp
  (use-package visual-regexp-steroids
    :ensure t
    :if (executable-find "python3")
    :init
    (require 'visual-regexp-steroids))
#+end_src
**** ~undo-fu~: Better Undo
Emacs undo can be confusing and it also doesn't persist for all of time, which is an amazing thing to have. Let's add that.
#+begin_src emacs-lisp
  (use-package undo-fu
    :ensure t
    :init
    (global-unset-key (kbd "C-z"))
    (global-set-key (kbd "C-z")   'undo-fu-only-undo)
    (global-set-key (kbd "C-S-z") 'undo-fu-only-redo)
    ;; we have like so much ram nowadays
    (setq undo-limit 67108864)
    (setq undo-strong-limit 100663296)
    (setq undo-outer-limit 1006632960))

  (use-package undo-fu-session
    :ensure t
    :diminish
    :init
    (undo-fu-session-global-mode))
#+end_src
**** ~vundo~: Undo in a Tree
It's hard to mentally picture all the undos, but since we already have infinity undo state, it might be nice to do that
#+begin_src emacs-lisp
  (use-package vundo
    :ensure t
    :init
    (setq diff-switches "-u --color=never")
    (setq vundo-glyph-alist vundo-unicode-symbols))
#+end_src
**** ~yasnippet~: Dynamic templates, replace the macro system
This saves typing a lot of the same things over and over again by automatically completing them. This is really useful in more verbose languages.
#+begin_src emacs-lisp
  (use-package yasnippet
    :ensure t
    :diminish yas-mode
    :config
    (yas-global-mode 1))

  ;; the actual snippets
  (use-package yasnippet-snippets
    :ensure t
    :after yasnippet)
#+end_src
What's really nice is that we don't even really need to know them. We can just magically filter through them with some good old fashioned ~completion-at-point~ magic:
#+begin_src emacs-lisp
  (use-package yasnippet-capf
    :ensure t
    :after cape
    :config
    (add-to-list 'completion-at-point-functions #'yasnippet-capf))
#+end_src
**** ~tree-sitter~: Every Major Mode
This is technically in Emacs now, but the version it ships with can sometimes be woefully out of date.
#+begin_src emacs-lisp
  (use-package tree-sitter
    :ensure t
    :diminish
    :config
    (global-tree-sitter-mode)
    (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode))

  (use-package tree-sitter-langs
    :ensure t
    :after tree-sitter)
#+end_src
Of course, once it's installed, we want to replace our modes. If this fails, make sure to run ~M-x treesit-install-language-grammar~ per language.
TODO: add more langs in there
#+begin_src emacs-lisp
(setq major-mode-remap-alist
      '((python-mode . python-ts-mode)
        (rust-mode . rust-ts-mode)
        (c-mode . c-ts-mode)
        (c++-mode . c++-ts-mode)
        (js-mode . js-ts-mode)))
#+end_src
**** ~disproject~: Transient ~project.el~
Transient interfaces are great! They are amazing to use in ~magit~, this brings them into ~project~ so that I actually remember to use it.
#+begin_src emacs-lisp
  (use-package disproject
    :ensure t
    :bind (:map ctl-x-map
	    ("p" . disproject-dispatch)))
#+end_src
**** ~macrostep~: Expand Emacs Lisp Macros
An incredibly useful feature for debugging Elisp, this lets you step through a macro as it's being evaluated. This can help a lot with nested macros, as otherwise the sequence of operations can be quite confusing.
#+begin_src emacs-lisp
  (use-package macrostep
    :ensure t)
#+end_src
**** ~easysession~: Replacement of ~desktop.el~
~desktop.el~ is slow, annoying, and makes getting out of Emacs in a hurry a real pain. This is much faster:
#+begin_src emacs-lisp
  (use-package easysession
    :ensure t
    :custom
    (easysession-save-interval (* 3 60)) ;; once every 3 minutes
    (easysession-save-mode-lighter-show-session-name t)
    (easysession-save-mode-line-misc-info t)
    :init
    (add-hook 'emacs-startup-hook #'easysession-load-including-geometry 102)
    (add-hook 'emacs-startup-hook #'easysession-save-mode 103))
#+end_src
And bind it under ~C-c r~ because it's short for restore in my mind:
#+begin_src emacs-lisp
  ;; Main keybindings
  (global-set-key (kbd "C-c r l") 'easysession-switch-to) ;; load
  (global-set-key (kbd "C-c r s") 'easysession-save-as) ;; save

  ;; Other keybindings
  (global-set-key (kbd "C-c r L") 'easysession-switch-to-and-restore-geometry)
  (global-set-key (kbd "C-c r d") 'easysession-delete)
  (global-set-key (kbd "C-c r r") 'easysession-rename)
  (global-set-key (kbd "C-c r R") 'easysession-reset)
#+end_src
*** Packages: Additions
These packages add brand-new features and modes to Emacs.
**** ~smog~: Reading Quality
Emacs doesn't have a feature like Microsoft Word to check for ease of reading... until now. Highly usable for a variety of writing tasks, it gives a good score about how readable a buffer is. Just call it to get a bunch of info on writing sins.
#+begin_src emacs-lisp
  (use-package smog
    :ensure t)
#+end_src
**** ~neotree~: Side Tree Menu
Now I'm aware that ~treemacs~ exists but it's too big and bloated for my liking. I want something fast and easy to use that also works on console. This is it.
#+begin_src emacs-lisp
  (use-package neotree
    :ensure t
    :init
    (setq neo-theme 'ascii))
#+end_src
**** ~magit~: A Git Client
A complete Git client is a pretty amazing thing.
#+begin_src emacs-lisp
  (use-package magit
    :ensure t
    :bind ("C-x g" . magit-status))
#+end_src
We'll also grab a few bonus features as well:
#+begin_src emacs-lisp
  (use-package magit-todos
    :ensure t
    :after magit
    :diminish
    :init
    (magit-todos-mode 1))
#+end_src
**** ~forge~: A Git Forge Client
Like ~magit~ but for GitHub. Invaluable.
#+begin_src emacs-lisp
  ;; needed for github secret
  (setq auth-sources '("~/.authinfo"))

  (use-package forge
    :ensure t
    :after magit)
#+end_src
**** ~gptel~: LLMs in Emacs
I don't use this very often, but it solves a very serious problem of Emacs missing some serious features (like proper grammar checking and semantic debugging). This remedies that, but I'm still trying to find a good balance to it.
#+begin_src emacs-lisp
  (use-package gptel
    :ensure t
    :config
    (setq gptel-model 'gemma4:e4b-mlx
  	gptel-backend (gptel-make-ollama "Ollama"
  	 :host "localhost:11434"
  	 :stream t
  	 :models '(gemma4:12b-mlx gemma4:e4b-mlx))))
#+end_src
**** ~igist~: GitHub Gist Client
It's useful for quickly sharing code with someone, and has a nice transient interface. This is probably the best solution for collaborating on a document, which Emacs still can't really do yet.
#+begin_src emacs-lisp
  (use-package igist
    :ensure t)
#+end_src
**** ~atomic-chrome~: Emacs in Browser
So Emacs is great, but its built in web browser (~xwidget-webkit~) is not the best. What's the fix? Simple. Use GhostText and this package to chain the gap, so that we can pop open Emacs on any buffer on the web! It's especially good in cases where you want to use syntax highlighting for something. But it only works on desktop operating systems. For Safari mostly. If you want better for Chrome and Firefox, use ~chrome-emacs~.
#+begin_src emacs-lisp
  (use-package atomic-chrome
    :if (and (or *is-a-mac* *is-a-linux*) window-system) 
    :ensure t
    :init
    (atomic-chrome-start-server))
#+end_src
**** ~multiple-cursors~: Edit (At Scale)
This is a crazy package. You can basically select everything you want in one fell swoop, and it makes it extremely easy to do mass editing. Way, way better than the VSCode implementation of this feature (you don't even need to select the same feature, Emacs does it for you). 
#+begin_src emacs-lisp
  (use-package multiple-cursors
    :ensure t
    :bind (("C-S-c C-S-c" . mc/edit-lines)
	   ("C->" . mc/mark-next-like-this)
	   ("C-<" . mc/mark-previous-like-this)
	   ("C-c C-<" . mc/mark-all-like-this)))
#+end_src
**** ~binky~: Jumping Cursor
This is another crazy package. You can select many different cursor positions as registers, marked with single keys, and jump around to them. it's a lot like Vim's feature for this, but better because it's got really good memory.
#+begin_src emacs-lisp
  (use-package binky
    :ensure t
    :bind (("C-c b b" . binky-binky)
	   ("C-c b c" . binky-clean)
	   ("C-c b s" . binky-save)
	   ("C-c b r" . binky-restore)
	   ("C-c b n" . binky-next-in-buffer)
	   ("C-c b p" . binky-previous-in-buffer))
    :init
    (progn
      (binky-mode)
      (binky-margin-mode)))
#+end_src
**** ~move-dup~: Rectangular Edit
This is amazing because it basically lets you drag and drop text without ever lifting your hand and using the mouse. Quite like the lazy copy-paste that some people do but without sloppily using the mouse. It's ~M~ and arrows for moving lines, ~C-M~ and arrows for duplicating the same line down.
#+begin_src emacs-lisp
  (use-package move-dup
    :ensure t
    :diminish
    :init
    (global-move-dup-mode))
#+end_src
**** ~expand-region~: Semantic Selection
This is a lot faster than using the standard text commands. This one selects by semantic regions, so it's quite a lot faster.
#+begin_src emacs-lisp
  (use-package expand-region
    :ensure t
    :bind ("C-=" . er/expand-region))
#+end_src
**** ~docker~: Docker Client
Docker is a terrible piece of software that should never be used. But yet.
#+begin_src emacs-lisp
  (use-package docker
    :ensure t)
#+end_src
**** ~git-timemachine~: Git Time Travel
Does exactly what it says. Has some weird default settings.
#+begin_src emacs-lisp
  (use-package git-timemachine
    :ensure t)
#+end_src
**** ~git-link~: View Online Git
This is nice because it plays well with ~git-timemachine~, so it really does work on any given buffer for Git. 
#+begin_src emacs-lisp
  (use-package git-link
    :ensure t
    :config
    (global-set-key (kbd "C-c g l") 'git-link))
#+end_src
**** ~why-this~: Git Blame Client
This package adds a few functions which annotate the buffer with Git blames, so you can see exactly who edited what. Useful for figuring out when a change was applied. Disabled by default due to it being annoying in the buffer.
#+begin_src emacs-lisp
  (use-package why-this
    :ensure t
    :diminish)
#+end_src
**** ~smeargle~: Age At A Glance
When activated, you can see the age of a given line (in Git-controlled buffers).
#+begin_src emacs-lisp
  (use-package smeargle
    :ensure t)
#+end_src
**** ~diff-hl~: Changes in Fringes
Shows what has changed between Git commits. This doesn't work without a graphical frame and it doesn't work on non-version controlled files. It's in the right fringe because nothing useful ever happens there and that's where we want all that good info anyways.
#+begin_src emacs-lisp
  (use-package diff-hl
    :ensure t
    :if window-system
    :hook (after-init . global-diff-hl-mode)
    :diminish global-diff-hl-mode
    :custom
    (diff-hl-disable-on-remote t)
    (diff-hl-margin-symbols-alist
     '((insert . "+")
       (delete . "-")
       (change . "*")
       (unknown . "?")
       (ignored . "i")))
    :init
    (setq-default diff-hl-side 'right))

#+end_src
**** ~treesit-fold~: Folding in Fringes
So shockingly Emacs doesn't ship with code folding outside of Org. This fixes this. Fold with shift-tab.
#+begin_src emacs-lisp
  (use-package treesit-fold
    :ensure t
    :diminish global-treesit-fold-indicators-mode
    :bind
    (:map treesit-fold-mode-map
	  ("<backtab>" . treesit-fold-toggle))
    :init
    (setq treesit-fold-line-count-show t
	  treesit-fold-line-count-format " <%d lines> ")
    (global-treesit-fold-indicators-mode))
#+end_src
**** ~flycheck~: Frontend to ~lsp-mode~
In modern Emacs, the LSP server handles all the actual work of linting, fixing, and correcting our code. We hand off the actually challenging tasks to it, but still need some nice features to go through what it says it's doing. So we add this in.
#+begin_src emacs-lisp
  (use-package flycheck
    :ensure t)
#+end_src
**** ~lsp-mode~: Language Server Protocol support
It's pretty good these days, but the choice to make ~company~ mandatory was very strange.
#+begin_src emacs-lisp
  (use-package lsp-mode
    :ensure t
    :hook (lsp-completion-mode . (lambda ()
  				 (setq-local completion-at-point-functions
  					     (list (cape-capf-super #'lsp-completion-at-point
  								    #'yasnippet-capf)
  						   #'cape-file))))
    :bind
    (:map lsp-mode-map
  	  ("C-c d" . lsp-describe-thing-at-point)
  	  ("C-c u" . lsp-ui-imenu)
  	  ("M-i" . lsp-ui-doc-focus-frame)))
#+end_src
**** ~dape~: Debug Adapter Protocol support
Probably the best debugging option that isn't torturous to use. Only works on a relatively minimal set of compiled languages at the time of writing.
#+begin_src emacs-lisp
  (use-package dape
    :ensure t
    :hook
    (kill-emacs . dape-breakpoint-save)
    (after-init . dape-breakpoint-load)
    :custom
    (dape-breakpoint-global-mode +1)
    :config
    (setq dape-buffer-window-arrangement 'gud))
#+end_src
**** ~mindstream~: Summon Scratch
This quickly creates a content-addressed, day-specific, arbitrary text file that can be used for just about anything. It's quite fantastic, but needs a few changes.
#+begin_src emacs-lisp
  (use-package mindstream
    :ensure t
    :custom
    (mindstream-persist t)
    :config
    ;; save to $HOME/Documents/Scratch
    (let ((outpath (expand-file-name "~/Documents/Scratch")))
      (setq mindstream-path outpath)
      (setq mindstream-save-session-path outpath))
    (mindstream-mode))
#+end_src
**** ~disaster~: Disassemble C and Fortran
Very easy in-buffer reference for Fortran and C code. Doesn't work over TRAMP, so it's mostly useful for local-machine debugging only.
#+begin_src emacs-lisp
  (use-package disaster
    :ensure t
    :config
    :bind (:map c-mode-map
  	 ("C-c d" . disaster)
  	 :map fortran-mode-map
  	 ("C-c d" . disaster)))
#+end_src
**** Language: LaTeX
LaTeX is very cool and Emacs is really, really good at this mode nowadays. Let's set up a nicer environment first:
#+begin_src emacs-lisp
  ;; the all purpose LaTeX environment
  (use-package auctex
    :ensure t
    ;; the weird name diffs it from the default installed one
    :hook ((LaTeX-mode . outline-minor-mode) ;; tab through our document like Org
	   (LaTeX-mode . prettify-symbols-mode) ;; math looks way nicer
	   (LaTeX-mode . LaTeX-math-mode) ;; make math nicer
	   (LaTeX-mode . visual-line-mode)
	   (LaTeX-mode . TeX-PDF-mode))
    :config
    (setq-default TeX-auto-save t
		  TeX-parse-self t
		  TeX-save-query nil
		  TeX-preview-default nil
		  TeX-source-correlate-method 'synctex
		  TeX-source-correlate-start-server t
		  TeX-view-program-selection '((output-pdf "PDF Tools"))
		  TeX-view-program-list '(("PDF Tools" TeX-pdf-tools-sync-view)))
    (add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer))

  ;; use TAB to jump around the mode really, really fast
  (use-package cdlatex
    :ensure t
    :after auctex
    :diminish 
    :hook (LaTeX-mode . turn-on-cdlatex))
#+end_src
Cool. Now let's set up automatic previews: 
#+begin_src emacs-lisp
  (defun personal/latex-auto-compile ()
    (when (eq major-mode 'LaTeX-mode)
      (TeX-save-document (TeX-master-file))
      (TeX-command "LaTeX" 'TeX-master-file -1)))

  (add-hook 'after-save-hook #'personal/latex-auto-compile)
#+end_src
**** Language: MATLAB
To be honest, I think I can make this do more, such as having MATLAB as a language server. How exactly is a bit difficult. This code seems to maybe have some answers? https://github.com/karthink/.emacs.d/blob/master/init.el#L1660

TODO: improve this
#+begin_src emacs-lisp
  (use-package matlab-mode
    :ensure t)
#+end_src
**** Language: Python
The actual mode is bundled with Emacs, but the default interpreter is trash. Let's use the better one:
#+begin_src emacs-lisp
  (when (executable-find "ipython")
    (setq python-shell-interpreter "ipython"
	  python-shell-interpreter-args "-i --simple-prompt"))
#+end_src
Basically a requirement to use with uv:
#+begin_src emacs-lisp
  (use-package uv-mode
    :ensure t
    :diminish
    :init
    (uv-mode))
#+end_src
This is also useful for ~lsp-mode~:
#+begin_src emacs-lisp
  (use-package lsp-pyright
    :ensure t
    :hook (python-mode . (lambda ()
			   (require 'lsp-pyright)
			   (lsp-deferred))))
#+end_src
Then do very lazy autoformatting with Ruff at save-time.
#+begin_src emacs-lisp
  (use-package ruff-format
    :ensure t
    :diminish
    :hook ((python-mode . ruff-format-on-save-mode)
  	 (python-ts-mode . ruff-format-on-save-mode)))
#+end_src
Also, we need a hook to keep flycheck around just for ruff:
#+begin_src emacs-lisp
(add-hook 'lsp-after-open-hook
          (lambda ()
            (when (derived-mode-p 'python-mode)
              (flycheck-add-next-checker 'lsp '(warning . python-ruff)))))
#+end_src
This lets us edit PIP requirements:
#+begin_src emacs-lisp
  (use-package pip-requirements
    :ensure t)
#+end_src
**** Language: R
R is always going to be subpar in Emacs, but we can make it at least mildly less painful to use. ESS is okay I guess? I'd much rather use RStudio instead though.
#+begin_src emacs-lisp
  (use-package ess
    :ensure t
    :init
    (require 'ess-r-mode))
#+end_src
**** Language: C#/.NET
This is for project files. The core language itself is a part of Emacs since version 29.0:
#+begin_src emacs-lisp
  (use-package csproj-mode
    :ensure t)
#+end_src
**** Language: HTML/CSS/JS/TS
These languages are terrible, fortunately ~skewer-mode~ is great and lets you use all of them in the same buffer all at once, and even summons a web server for you:
#+begin_src emacs-lisp
  (use-package skewer-mode
    :ensure t)
#+end_src
Also, Emacs doesn't ship with native TypeScript support:
#+begin_src emacs-lisp
  (use-package typescript-mode
    :ensure t)
#+end_src
**** Language: Go
The mode doesn't come with Emacs:
#+begin_src emacs-lisp
  (use-package go-mode
    :ensure t
    :config
    (add-hook 'before-save-hook 'gofmt-before-save)
    :init
    ;; fix annoying issues with GOPATH
    (setenv "GOPATH" (concat (getenv "HOME") "/.go")))
#+end_src
**** Language: Markdown
No mode for it by default:
#+begin_src emacs-lisp
  (use-package markdown-mode
    :ensure t)
#+end_src
Also, with some cool magic we can use ~eww~ to preview what it'll look like if we're writing a GitHub ~README.md~, using this package:
#+begin_src emacs-lisp
  (use-package gh-md
    :ensure t)
#+end_src
**** Language: Rust
The mode doesn't come with Emacs, plus we'd like the newest one always:
#+begin_src emacs-lisp
  (use-package rust-mode
    :ensure t)
#+end_src
**** Language: Nix
This mode brings a lot to the table, but almost never actually need all it brings.
#+begin_src emacs-lisp
  (use-package nix-mode
    :ensure t
    :mode "\\.nix\\'")
#+end_src
**** Language: Common Lisp
It's a shockingly nice language that I don't get to use often enough. In the event that I do write some more, it's nice to have the best IDE for it:
#+begin_src emacs-lisp
  (use-package sly
    :ensure t)

  (use-package sly-macrostep
    :ensure t)

  (use-package sly-repl-ansi-color
    :ensure t
    :after sly
    :init
    (push 'sly-repl-ansi-color sly-contribs))
#+end_src
*** Packages: Misc Modes
These are all the things that are needed for occasional, one-off editing and rarely matter all that much. They're kept around because on that blue moon where I actually need to edit one of these obscure types in Emacs, it's there.
**** Mode: Cask
For developing Elisp, not the one used in macOS Homebrew.
#+begin_src emacs-lisp
  (use-package cask-mode
    :ensure t)
#+end_src emacs-lisp
**** Mode: Lua
#+begin_src emacs-lisp
  (use-package lua-mode
    :ensure t
    :mode "\\.lua\\'")
#+end_src emacs-lisp
**** Mode: CMake
#+begin_src emacs-lisp
  (use-package cmake-mode
    :ensure t)
#+end_src
**** Mode: Yarn
#+begin_src emacs-lisp
  (use-package yarn-mode
    :ensure t)
#+end_src
**** Mode: Apache Config
#+begin_src emacs-lisp
  (use-package apache-mode
    :ensure t)
#+end_src
**** Mode: BASIC
Hopefully this will never, ever be needed.
#+begin_src emacs-lisp
  (use-package basic-mode
    :ensure t
    :mode "\\.bas\\'")
#+end_src
**** Mode: AppleScript
AppleScript is not great.
#+begin_src emacs-lisp
  (use-package applescript-mode
    :ensure t
    :init
    (add-to-list 'auto-mode-alist '("\\.applescript$" . applescript-mode)))
#+end_src
**** Mode: Crontab
#+begin_src emacs-lisp
  (use-package crontab-mode
    :ensure t
    :mode "\\.crontab\\'")
#+end_src
**** Mode: Vimrc
#+begin_src emacs-lisp
  (use-package vimrc-mode
    :ensure t
    :mode "\\.vimrc\\.virc\\'")
#+end_src
**** Mode: Systemd Config
#+begin_src emacs-lisp
  (use-package systemd
    :ensure t
    :mode "\\.unit\\.service\\'")

  (use-package journalctl-mode
    :ensure t)
#+end_src
**** Mode: Git Config
#+begin_src emacs-lisp
  (use-package git-modes
    :ensure t
    :mode "\\.gitconfig\\'")
#+end_src
**** Mode: DHall
#+begin_src emacs-lisp
  (use-package dhall-mode
    :ensure t
    :mode "\\.dhall\\'")
#+end_src
**** Mode: CSV Files
#+begin_src emacs-lisp
  (use-package csv-mode
    :ensure t
    :mode "\\.[Cc][Ss][Vv]\\'"
    :config
    (setq csv-separators '("," ";" "|" " ")))
#+end_src
**** Mode: JSON Files
#+begin_src emacs-lisp
  (use-package json-mode
    :ensure t
    :mode "\\.json\\'")
#+end_src
**** Mode: YAML Files & Ansible
So we can do this to get the basic modes:
#+begin_src emacs-lisp
  (use-package yaml-mode
    :ensure t
    :mode "\\.yml\\.erb\\'")

  (use-package ansible
    :ensure t
    :init
    (add-hook 'yaml-mode-hook '(lambda () (ansible-mode 1))))
#+end_src
I used the polymode in the past, but it costs way too much in startup time. Would not recommend.
**** Mode: Unix Log
#+begin_src emacs-lisp
  (use-package logview
    :ensure t)
#+end_src
**** Mode: Jinja2
#+begin_src emacs-lisp
  (use-package jinja2-mode
    :ensure t
    :mode "\\.j2\\'")
#+end_src
**** Mode: phpBB
#+begin_src emacs-lisp
  (use-package bbcode-mode
    :ensure t)
#+end_src
**** Mode: Standard ENV File
#+begin_src emacs-lisp
  (use-package dotenv-mode
    :ensure t
    :mode "\\.env\\'")
#+end_src
**** Mode: Standard INI File
#+begin_src emacs-lisp
  (use-package ini-mode
    :ensure t
    :mode "\\.ini\\'")
#+end_src
**** Mode: AutoHotKey
#+begin_src emacs-lisp
  (use-package ahk-mode
    :ensure t
    :mode "\\.ahk\\'")
#+end_src
**** Mode: Dockerfile
#+begin_src emacs-lisp
  (use-package dockerfile-mode
    :ensure t)
#+end_src
**** Mode: AppArmor Config
#+begin_src emacs-lisp
  (use-package apparmor-mode
    :ensure t
    :init
    (require 'apparmor-mode))
#+end_src
**** Mode: FVWM Config
#+begin_src emacs-lisp
  (use-package fvwm-mode
    :ensure t
    :mode "\\.fvwm\\'")
#+end_src
**** Mode: tmux Config
#+begin_src emacs-lisp
  (use-package tmux-mode
    :ensure t
    :mode "\\.tmux.conf\\'")
#+end_src
**** Mode: robots.txt
#+begin_src emacs-lisp
  (use-package robots-txt-mode
    :ensure t
    :init
    (add-to-list 'auto-mode-alist '("robots.txt" . robots-txt-mode)))
#+end_src
**** Mode: PowerShell
#+begin_src emacs-lisp
  (use-package powershell
    :ensure t
    :mode "\\.ps1\\'")
#+end_src
*** End
This is a good snippet to have right at the end, so that we know exactly how long it took to read the parsed file and execute it into Emacs.

However, it's important to note that this doesn't fully capture the length of init-time, as ~elpaca~ can load lazily.
#+begin_src emacs-lisp
(message "[init.el] Startup finished in: %s" (emacs-init-time))
#+end_src
