* Personal Emacs Configuration 🏡
This repository contains the setup for an Emacs configuration, tailored for my use. It has features well suited for:
- Rust
- Common Lisp
- Python
- General editing

It works best on macOS and in a graphical frame. For the best experience, use Mitsuharu's Emacs macOS port, or a pureGTK build on Linux. Currently, it works on Emacs versions `29` and `28`.

The whole configuration lives in this file, so just scroll down!

** How to Install 💻
Firstly, make sure the following programs are installed:
- `python`, any version that's not `python2`
- `ripgrep` (optional)
- `git` (used by `straight.el` for managing packages)
- `gcc` and `cmake`, used for `vterm` (optional)
- `fish`, used to make completion files for `eshell` (optional)
- `aspell`, used for enabling spellcheck (optional)
- Any specific language servers/packages needed by certain modes:
  - Shell: `checkbashisms`
  - LaTeX: `texlab`
  - Common Lisp: `sbcl`
  - Markdown: `markdown`
  - Rust: `rust-analyzer`
  - Python: `black`
  - Go: `gopls`
  
Ideally in a future version of this config, it would prompt you to install these, but that's currently not the case.

`git clone` this into `~/.emacs.d`, then start Emacs. This will take some time on initial startup, but after the first boot this process should become substantially faster. It works on *my* machine, but I make no guarantees that this will be the case on yours!
** Things To Improve 🤔
- The theming situation needs some work
- Using less packages is desirable
** The Actual Configuration 📖
*** Package Management
The default ~package.el~ is disabled by ~early-init.el~. Let's now configure something new, that being Elpaca.
*** TODO...





